steps:
#  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#    entrypoint: 'gcloud'
#    timeout: 240s
#    args: ['builds', 'list']

#  - name: 'ubuntu'
#    script: |
#      export token=$(gcloud auth print-access-token)
#      export project=$(gcloud config get-value project | head -n 1)
#      export region=us-central1
#
#  - name: 'us-docker.pkg.dev/appintegration-toolkit/images/integrationcli'
#    entrypoint: 'integrationcli'
#    timeout: 240s
#    args: ['prefs', 'set', '-p', '$project', '-r', '$region', '-t', '$token']
#


#  - name: 'ubuntu'
#    entrypoint: 'sh'
#    args:
#      - '-c'
#      - |
#        export token=$(gcloud auth print-access-token)
#        export project=$(gcloud config get-value project | head -n 1)
#        export region=us-central1
#    timeout: 240s
#
#
#  - name: 'us-docker.pkg.dev/appintegration-toolkit/images/integrationcli'
#    entrypoint: 'integrationcli'
#    timeout: 240s
#    args: ['prefs', 'set', '-p', '$project', '-r', '$region', '-t', '$token']

  - name: 'gcr.io/cloud-builders/bash'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "token=$(gcloud auth print-access-token)" > /workspace/vars.env
        echo "project=$(gcloud config get-value project | head -n 1)" >> /workspace/vars.env
        echo "region=us-central1" >> /workspace/vars.env

  - name: 'us-docker.pkg.dev/appintegration-toolkit/images/integrationcli'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/vars.env
        integrationcli --token "$token" --project "$project" --region "$region"
    timeout: 240s