steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - poc-function-deployment
      - --region=us-central1
      - --source=./cloud-function
      - --trigger-http
      - --runtime=nodejs20
      - --set-env-vars
      - MY_SECRET=$_MY_SECRET_LATEST,MY_ULTRA_SECRET=$_MY_SUPER_SECRET_LATEST
      - --gen2
#  - name: 'gcr.io/cloud-builders/gcloud'
#    entrypoint: 'bash'
#    args:
#      - '-c'
#      - |
#        # Authenticate to Google Cloud
#        gcloud auth configure-docker us-docker.pkg.dev
#
#        # Set multiple variables
#        token=$(gcloud auth print-access-token)
#        project=$(gcloud config get-value project | head -n 1)
#        region="us-central1"
#
#        # Write variables to a file
#        echo "token=${token}" >> /workspace/env_vars.txt
#        echo "project=${project}" >> /workspace/env_vars.txt
#        echo "region=${region}" >> /workspace/env_vars.txt
#
#  - name: 'us-docker.pkg.dev/appintegration-toolkit/images/integrationcli:latest'
#    entrypoint: 'sh'
#    args:
#      - '-c'
#      - |
#
#        # Load the variables
#        source /workspace/env_vars.txt
#
#        integrationcli prefs set -p "$project" -r "$region" -t "$token"
#
#        # Run the first integrationcli command
#        integrationcli integrations apply -f . -e dev --wait=true --verbose
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  env:
    - MY_DEV_SECRET=t1
    - MY_DEV_SUPER_SECRET=t2
substitutions:
  _MY_SECRET_LATEST: $MY_DEV_SECRET
  _MY_SUPER_SECRET_LATEST: $MY_DEV_SUPER_SECRET
