steps:
#  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#    entrypoint: 'gcloud'
#    timeout: 240s
#    args: ['builds', 'list']

#  - name: 'ubuntu'
#    script: |
#      export token=$(gcloud auth print-access-token)
#      export project=$(gcloud config get-value project | head -n 1)
#      export region=us-central1
#
#  - name: 'us-docker.pkg.dev/appintegration-toolkit/images/integrationcli'
#    entrypoint: 'integrationcli'
#    timeout: 240s
#    args: ['prefs', 'set', '-p', '$project', '-r', '$region', '-t', '$token']
#


  - name: 'ubuntu'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        export token=$(gcloud auth print-access-token)
        export project=$(gcloud config get-value project | head -n 1)
        export region=us-central1
        echo $token
    timeout: 240s


  - name: 'us-docker.pkg.dev/appintegration-toolkit/images/integrationcli'
    entrypoint: 'integrationcli'
    timeout: 240s
    args: ['prefs', 'set', '-p', '$project', '-r', '$region', '-t', '$token']