steps:
#  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#    entrypoint: 'gcloud'
#    timeout: 240s
#    args: ['builds', 'list']

  - name: 'us-docker.pkg.dev/appintegration-toolkit/images/integrationcli'
    script: |
      #!/usr/bin/sh
      echo "Downloading integrationcli"
      token=$(gcloud auth print-access-token)