on: push

jobs:
  job_id:
    runs-on: ubuntu-latest
    container:
      image: us-docker.pkg.dev/appintegration-toolkit/images/integrationcli:latest
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: 'Test integrationcli'
        run: 'integrationcli integrations list'